import { Component, OnInit, Provider } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { HttpHeaders } from '@angular/common/http';
import { MatDialog } from '@angular/material/dialog';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  asIsOrder(a, b) {
    return 1;
  }
  isDataLoaded = false;
  title = 'userDetails';
  accessToken: any;
  userDetails: any;
  parentData: any = [];
  immediateChild: any = [];
  secondChild: any = [];
  thirdChild: any = [];
  mainData: any;
  keys = {
    name: 'Name',
    userId: 'User ID',
    username: 'Username',
    // fName: 'Family Name',
    email: 'Email ID',
    contact: 'Contact',
    created: 'Created On',
  };
  demoData = [
    {
      userId: 10235,
      imsuserId: 'b3412e04-ea87-40aa-a3ef-ad6c1ef1ec03',
      name: 'sumanworknew',
      familyName: 'saaaw',
      userName: 'aruns11awaa1@gmail.com',
      emailIdPrimary: 'aruns11awaa1@gmail.com',
      contactNumberPrimary: '1803123141',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-17T05:00:47.8871657+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 3,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10234,
      imsuserId: '670289ca-d577-4eae-a006-853e4d69a993',
      name: 'sdvz',
      familyName: 'fb z',
      userName: 'sdvsd@asd.asc',
      emailIdPrimary: 'sdvsd@asd.asc',
      contactNumberPrimary: '1245746985',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-16T06:22:47.2110886+00:00',
      parentId: 10203,
      isActive: 1,
      timeZoneId: 13,
      languageId: 1,
      dataAccessTypeId: 3,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10233,
      imsuserId: 'faf7edad-76ec-47c6-9e16-00d0dced87bc',
      name: 'TTTT',
      familyName: 'EESTR',
      userName: 'sam@tesst2.com',
      emailIdPrimary: 'sam@tesst2.com',
      contactNumberPrimary: '1452367810',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-15T13:45:22.6837332+00:00',
      parentId: 10229,
      isActive: 1,
      timeZoneId: 15,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10232,
      imsuserId: 'eb93e33f-7f64-4824-8387-264aadfb3809',
      name: 'Sanjiv',
      familyName: 'PC',
      userName: 'sanjiv@test.com',
      emailIdPrimary: 'sanjiv@test.com',
      contactNumberPrimary: '1452698753',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-15T09:02:52.4379766+00:00',
      parentId: 10115,
      isActive: 1,
      timeZoneId: 10,
      languageId: 1,
      dataAccessTypeId: 3,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10231,
      imsuserId: 'edf1711f-1054-4068-9b48-51c7b00aec4f',
      name: 'Sam',
      familyName: 'TestPC',
      userName: 'sam@test1.com',
      emailIdPrimary: 'sam@test1.com',
      contactNumberPrimary: '1234150297',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-15T08:54:41.1214836+00:00',
      parentId: 10142,
      isActive: 1,
      timeZoneId: 12,
      languageId: 1,
      dataAccessTypeId: 3,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10230,
      imsuserId: '622dc747-574a-4450-a04c-b2aaeb03365b',
      name: 'User New',
      familyName: 'New',
      userName: 'test@asdfc.dc',
      emailIdPrimary: 'test@asdfc.dc',
      contactNumberPrimary: '9874125630',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-15T08:44:12.617313+00:00',
      parentId: 10201,
      isActive: 1,
      timeZoneId: 15,
      languageId: 1,
      dataAccessTypeId: 3,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10229,
      imsuserId: '9bb92573-67aa-4c32-a6b0-d7135244d6a4',
      name: 'latest1',
      familyName: 'latest1',
      userName: 'test@bag4.com',
      emailIdPrimary: 'test@bag4.com',
      contactNumberPrimary: 'test@bag4.com',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-09T19:02:21.4877984+00:00',
      parentId: 10228,
      isActive: 1,
      timeZoneId: 8,
      languageId: 1,
      dataAccessTypeId: 3,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10228,
      imsuserId: '91caf038-90a2-4b54-be30-d90e7836f32a',
      name: 'SamPC',
      familyName: 'SamTeast',
      userName: 'SAM@test.com',
      emailIdPrimary: 'SAM@test.com',
      contactNumberPrimary: '7845120148',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-09T12:14:37.8487739+00:00',
      parentId: 10149,
      isActive: 1,
      timeZoneId: 5,
      languageId: 1,
      dataAccessTypeId: 3,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10227,
      imsuserId: 'dcce38bc-3d76-42dc-b0a5-233126a8857a',
      name: 'Bag Update',
      familyName: 'Bag Update',
      userName: 'arunj11awaa1@gmail.com',
      emailIdPrimary: 'string',
      contactNumberPrimary: 'string',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-09T08:01:31.5474885+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 3,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10226,
      imsuserId: '03e1c67c-8937-41b4-bc1b-9db60ab5af15',
      name: 'Bag Update',
      familyName: 'Bag Update',
      userName: 'arunj11aaa1@gmail.com',
      emailIdPrimary: 'string',
      contactNumberPrimary: 'string',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-09T07:37:44.7173859+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 3,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10225,
      imsuserId: '98d1f59c-4ec7-4f04-a54a-be5502c97dca',
      name: 'aruns1aa',
      familyName: 'saa',
      userName: 'arunj11aa1@gmail.com',
      emailIdPrimary: 'arunj11aa1@gmail.com',
      contactNumberPrimary: '9854323141',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-09T07:34:27.718612+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10224,
      imsuserId: '87710b0b-3c03-4557-bc8d-dc7e85e76851',
      name: 'Bagpc123',
      familyName: 'bag pc',
      userName: 'arunj111@gmail.com',
      emailIdPrimary: 'arunj111@gmail.com',
      contactNumberPrimary: '01548759502',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-07T11:54:54.7215571+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 3,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10222,
      imsuserId: 'b4516d80-6ffa-47cb-9d45-a3bdc5fcd6c1',
      name: 'Bag',
      familyName: 'PC',
      userName: 'bag2@test.com',
      emailIdPrimary: 'bag2@test.com',
      contactNumberPrimary: '1478523690',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-07T11:28:02.1572155+00:00',
      parentId: 10222,
      isActive: 0,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 2,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10221,
      imsuserId: 'c2e0fc8a-66e6-45e2-8122-41acbc6c1750',
      name: 'BagPC',
      familyName: '123',
      userName: 'bag@test.com',
      emailIdPrimary: 'bag@test.com',
      contactNumberPrimary: '1231231289',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-07T11:25:41.0454186+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 17,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10220,
      imsuserId: '16acb196-bc38-4c81-b7c3-14f4b547c614',
      name: 'Fname ',
      familyName: 'Lname',
      userName: 'test2@test.com',
      emailIdPrimary: 'bag2@test.com',
      contactNumberPrimary: '1478523690',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-07T09:34:32.495366+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 2,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10219,
      imsuserId: 'bd7e689b-cb81-46cf-855c-51517c0329e1',
      name: 'vbsdf',
      familyName: 'fc vbgd',
      userName: 'test1@test.com',
      emailIdPrimary: 'test1@test.com',
      contactNumberPrimary: '9874563200',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-07T09:20:00.7243316+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 137,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10211,
      imsuserId: 'f1287ab9-9e73-4b24-8aee-87716b09e867',
      name: 'suman Eva-001',
      familyName: 'Eva-001',
      userName: 'eva1a2300@gmail.com',
      emailIdPrimary: 'aaac@gmail.com',
      contactNumberPrimary: '12324567899',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-06T08:05:21.0910777+00:00',
      parentId: 10114,
      isActive: 0,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 2,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10209,
      imsuserId: 'b5aa50c4-5326-41a4-8ef7-b1bd75d991e6',
      name: 'suman Eva-001',
      familyName: 'Eva-001',
      userName: 'eva1a230@gmail.com',
      emailIdPrimary: 'eva1a230@gmail.com',
      contactNumberPrimary: '01254856321',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-06T08:03:30.8704948+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10208,
      imsuserId: 'b674648d-7901-4e4a-83e2-b01daa2cf6ec',
      name: 'suman Eva-001',
      familyName: 'Eva-001',
      userName: 'eva1230@gmail.com',
      emailIdPrimary: 'eva1230@gmail.com',
      contactNumberPrimary: '0125485632',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-06T07:57:30.0652313+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10203,
      imsuserId: 'c6cb900a-d992-4359-8f21-dfb158a879a3',
      name: 'mohan',
      familyName: 'monty',
      userName: 'gg@dd',
      emailIdPrimary: null,
      contactNumberPrimary: '4563454567',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-03T16:27:44.557137+00:00',
      parentId: 10183,
      isActive: 0,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10202,
      imsuserId: 'fa0ee7ed-dc53-495f-a428-f5d7ac644a47',
      name: 'roger',
      familyName: 'khan',
      userName: 'hgy@fg',
      emailIdPrimary: 'hgy@fg',
      contactNumberPrimary: '6564564565',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-03T08:53:40.2174501+00:00',
      parentId: 10200,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10201,
      imsuserId: 'bd73086b-6a71-4538-be85-583dd9d10b11',
      name: 'testing ',
      familyName: 'role n team',
      userName: 'tr@gmail.com',
      emailIdPrimary: 'tr@gmail.com',
      contactNumberPrimary: '6786786789',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-03T08:46:53.2374031+00:00',
      parentId: 10182,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10200,
      imsuserId: '54d14534-a329-46a1-b5ab-14ed820c1095',
      name: 'noah',
      familyName: 'kop',
      userName: 'te@df',
      emailIdPrimary: 'te@df',
      contactNumberPrimary: '4567890999',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-03T08:18:30.275608+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10199,
      imsuserId: '1f25b65d-2354-4262-8278-b8731aaee783',
      name: 'test',
      familyName: 't',
      userName: 'gg@df',
      emailIdPrimary: 'gg@df',
      contactNumberPrimary: '4569997567',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-03T07:58:00.4301361+00:00',
      parentId: 10165,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10198,
      imsuserId: '0769616c-51ea-4d50-84fb-edcb7ee6741a',
      name: 'test',
      familyName: 'f',
      userName: 'hg@fg',
      emailIdPrimary: 'hg@fg',
      contactNumberPrimary: '4564564567',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-03T07:56:20.0826587+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10187,
      imsuserId: '34b6794e-5c72-4b26-b859-80c033a87db6',
      name: 'lolita',
      familyName: 's',
      userName: 'lalita068@gmail.com',
      emailIdPrimary: 'lalita068@gmail.com',
      contactNumberPrimary: '7878943214',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-03T07:43:39.980746+00:00',
      parentId: 10114,
      isActive: 0,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10183,
      imsuserId: 'eade6be5-615d-4424-a1fd-779abe816154',
      name: 'lalita',
      familyName: 's',
      userName: 'lalita06@gmail.com',
      emailIdPrimary: 'lalita096@gmail.com',
      contactNumberPrimary: '7879943214',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-02T00:49:51.2630987+00:00',
      parentId: 10114,
      isActive: 0,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10182,
      imsuserId: '4b911d22-15c2-4c9c-bcb7-e5aabeaf07f7',
      name: 'anjali',
      familyName: 's',
      userName: 'anjali@gmail.com',
      emailIdPrimary: 'anjali@gmail.com',
      contactNumberPrimary: '9879943214',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-02T00:44:43.156235+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10181,
      imsuserId: '68d676d7-caab-46fe-a56c-af61a398457f',
      name: 'mesha',
      familyName: 's',
      userName: 'mesha09@gmail.com',
      emailIdPrimary: 'mesha09@gmail.com',
      contactNumberPrimary: '9876943214',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-01T11:56:13.9898484+00:00',
      parentId: 10114,
      isActive: 0,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10180,
      imsuserId: '62ab2b05-39c1-44dc-8efb-472430c307d0',
      name: 'Harry',
      familyName: 'k',
      userName: 'harry089@gmail.com',
      emailIdPrimary: 'harry089@gmail.com',
      contactNumberPrimary: '8879654314',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-01T06:24:21.8084744+00:00',
      parentId: 10114,
      isActive: 0,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10179,
      imsuserId: '26277dd5-44a2-4bd2-8b00-7a3050f9b3a5',
      name: 'ajay',
      familyName: 'k',
      userName: 'aj089@gmail.com',
      emailIdPrimary: 'aj089@gmail.com',
      contactNumberPrimary: '9879654314',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-01T06:10:02.2134603+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10178,
      imsuserId: '46e9e39d-4a47-43a7-afc2-0f0a4cbee7b1',
      name: 'ajay',
      familyName: 'k',
      userName: 'aj09@gmail.com',
      emailIdPrimary: 'aj09@gmail.com',
      contactNumberPrimary: '9876543214',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-04-01T05:58:59.3036241+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10170,
      imsuserId: '9d099ba4-226c-4936-b4b5-f0bedad35be6',
      name: 'aruns',
      familyName: 's',
      userName: 'arunjdsds@gmail.com',
      emailIdPrimary: 'arunjdsds@gmail.com',
      contactNumberPrimary: '9870543214',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-03-30T07:45:59.4136293+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10166,
      imsuserId: '78b4fc38-8c65-40ea-b0c5-b772d0a7982d',
      name: 'aruns',
      familyName: 's',
      userName: 'arunj@gmail.com',
      emailIdPrimary: 'karunaj@gmail.com',
      contactNumberPrimary: '1234567899',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-03-29T03:52:38.0167715+00:00',
      parentId: 10114,
      isActive: 0,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 2,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10165,
      imsuserId: '0eaa81b9-c0c3-4c64-9bf2-57b95fe428de',
      name: 'aruns',
      familyName: 's',
      userName: 'arunk@gmail.com',
      emailIdPrimary: 'arunk@gmail.com',
      contactNumberPrimary: '9876543213',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-03-29T03:47:26.1894594+00:00',
      parentId: 10114,
      isActive: 0,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10164,
      imsuserId: '9a072d34-dd32-4c25-bafe-b70e56fbc3ac',
      name: 'aruns',
      familyName: 's',
      userName: 'arung@gmail.com',
      emailIdPrimary: 'arung@gmail.com',
      contactNumberPrimary: '9876543212',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-03-29T03:46:29.977116+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10163,
      imsuserId: 'ea01edd7-3316-4497-9ec2-e5f3a9332705',
      name: 'aruns',
      familyName: 's',
      userName: 'aruns@gmail.com',
      emailIdPrimary: 'aruns@gmail.com',
      contactNumberPrimary: '9876543211',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-03-29T03:38:20.6032168+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: 1,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10154,
      imsuserId: '1f57ec3e-594f-48f8-9eee-eba0abee7e37',
      name: 'Check',
      familyName: '1',
      userName: 'check@gmail.com',
      emailIdPrimary: 'check@gmail.com',
      contactNumberPrimary: '5555888841',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-02-20T08:43:56.0067009+00:00',
      parentId: 10117,
      isActive: 1,
      timeZoneId: 92,
      languageId: null,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10153,
      imsuserId: '880d9a3c-35e7-4a38-b040-f4a91fa77ead',
      name: 'Mail',
      familyName: 'Check',
      userName: 'mailcheck@gmail.com',
      emailIdPrimary: 'mailcheck@gmail.com',
      contactNumberPrimary: '7845852159',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-02-20T08:40:32.7509791+00:00',
      parentId: 10126,
      isActive: 1,
      timeZoneId: 92,
      languageId: null,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10150,
      imsuserId: 'b1157cf1-bf56-4d0b-ba13-10b5b215f268',
      name: 'sxcs',
      familyName: 'cdsxv ',
      userName: 'dsvbg@edf.dvfcdes',
      emailIdPrimary: 'dsvbg@edf.dvfcdes',
      contactNumberPrimary: '1111111111',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-02-18T10:28:34.5325061+00:00',
      parentId: 10149,
      isActive: 1,
      timeZoneId: 92,
      languageId: null,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10149,
      imsuserId: '423a88e9-9039-41dc-9260-b3981de4ea8e',
      name: 'Sam',
      familyName: 'PC',
      userName: 'sam-test@gmail.com',
      emailIdPrimary: 'sam-test@gmail.com',
      contactNumberPrimary: '0000000001',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-02-17T13:04:02.383782+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: null,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10142,
      imsuserId: 'dfb6896e-5414-4fd1-a44e-517216f73d7a',
      name: 'User-9',
      familyName: 'last-name',
      userName: 'test@test.com',
      emailIdPrimary: 'test@test.com',
      contactNumberPrimary: '1234567892',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-02-11T09:06:57.6540388+00:00',
      parentId: 10136,
      isActive: 1,
      timeZoneId: 92,
      languageId: null,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10137,
      imsuserId: '650cc1d8-74f7-4167-8911-2dc678cb4ecf',
      name: 'User-8',
      familyName: 'last-name',
      userName: 'sumantacustm@gmail.com',
      emailIdPrimary: 'sumantacustm@gmail.com',
      contactNumberPrimary: '8456986512',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-02-10T04:43:10.7628725+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: null,
      dataAccessTypeId: 3,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10136,
      imsuserId: 'eafe709b-b1e2-46e0-94cf-ed2fd01e3cec',
      name: 'User-7',
      familyName: 'last-name',
      userName: 'sumantabagnew@gmail.co',
      emailIdPrimary: 'sumantabagnew@gmail.co',
      contactNumberPrimary: '7548754875',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-02-10T04:36:13.5192287+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: null,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10126,
      imsuserId: 'a0fdb649-aef6-4b41-8c05-dbf9ffbbe50e',
      name: 'User-6',
      familyName: 'last-name',
      userName: 'hello@nwtwst.com',
      emailIdPrimary: 'hello@nwtwst.com',
      contactNumberPrimary: '7845123698',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-02-08T09:21:19.7200958+00:00',
      parentId: 10114,
      isActive: 1,
      timeZoneId: 92,
      languageId: null,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10119,
      imsuserId: 'e584d245-9a98-4cf0-924b-b7920a5b346f',
      name: 'User-5',
      familyName: 'last-name',
      userName: 'xcvxcv@gmail.com',
      emailIdPrimary: 'xcvxcv@gmail.com',
      contactNumberPrimary: '9999999963',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-01-22T09:16:36.3382824+00:00',
      parentId: 10118,
      isActive: 1,
      timeZoneId: 92,
      languageId: null,
      dataAccessTypeId: 3,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10118,
      imsuserId: 'e667940c-5677-4819-94bc-013d60fdb960',
      name: 'User-4',
      familyName: 'last-name',
      userName: 'sumantabag19@gmail.com1',
      emailIdPrimary: 'sumantabag19@gmail.com1',
      contactNumberPrimary: '0212321232',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-01-22T09:15:16.2348254+00:00',
      parentId: 10117,
      isActive: 1,
      timeZoneId: 92,
      languageId: null,
      dataAccessTypeId: 2,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10117,
      imsuserId: '48c6abd0-f6ad-4e72-bef6-6c0be79fe9ae',
      name: 'User-3',
      familyName: 'last-name',
      userName: 'sumantabag19@gmail.comc',
      emailIdPrimary: 'sumantabag19@gmail.comc',
      contactNumberPrimary: '0256564651',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-01-22T09:14:03.6263088+00:00',
      parentId: 10126,
      isActive: 1,
      timeZoneId: 92,
      languageId: null,
      dataAccessTypeId: 2,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10115,
      imsuserId: '3f3e7a0f-4a2f-42f3-bd4d-0906f3227877',
      name: 'User-2',
      familyName: 'last-name',
      userName: 'sumantabag19@gmail.comccc',
      emailIdPrimary: 'sumantabag19@gmail.comccc',
      contactNumberPrimary: '0254896521',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 10114,
      createdOn: '2021-01-20T12:09:27.5392666+00:00',
      parentId: 10149,
      isActive: 1,
      timeZoneId: 92,
      languageId: null,
      dataAccessTypeId: 1,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
    {
      userId: 10114,
      imsuserId: '2bc75b45-c4a6-4b7d-8a2f-86468530a86d',
      name: 'User-1',
      familyName: 'last-name',
      userName: 'sumantabag19@gmail.com',
      emailIdPrimary: 'sumantabag19@gmail.com',
      contactNumberPrimary: '0159515963',
      reportingManager: null,
      teamName: null,
      teamCount: 0,
      createdBy: 0,
      createdOn: '2021-01-20T11:13:55.9629996+00:00',
      parentId: 0,
      isActive: 1,
      timeZoneId: 92,
      languageId: null,
      dataAccessTypeId: 2,
      orgId: 3,
      currencyCode: null,
      currencyLocale: null,
      jobTitle: null,
      userHierarchy: null,
      teamUsers: null,
    },
  ];

  constructor(private http: HttpClient, public dialog: MatDialog) {}

  getAccessToken() {
    $('#userData').fadeOut();
    // Get access Token
    let tokenApiUrl =
      'https://authorizationserverapi20210311132545.azurewebsites.net/connect/token';
    let username = 'cdcdcdcdcd';
    let password = 'Suman123*';
    let scope = 'read write uiapi_all';
    let grant_type = 'password';
    let auth =
      'Basic RVZBLlVJLldFQjpzYzdGUWNiZ2Q2RWVzQ1padmRidWRkTnQ1dlEtMEFZLVZYYl84NDhQME1v';
    let body = `username=${username}&password=${password}&scope=${scope}&grant_type=${grant_type}`;
    let contentType = 'application/x-www-form-urlencoded';
    let options = {
      headers: new HttpHeaders({
        Authorization: auth,
        'Content-Type': contentType,
      }),
    };
    this.http.post(tokenApiUrl, body, options).subscribe((Response) => {
      if (Response) {
        console.log(Response);
        this.accessToken = Response['access_token'];
        this.getUserDetails(this.accessToken);
      }
    });
  }

  getUserDetails(token) {
    // Get User Details
    let userDetailsApiUrl =
      'https://evaapi20210311111013.azurewebsites.net/api/User/GetUsersByOrganization?orgId=3';
    let options = {
      headers: new HttpHeaders({
        Authorization: 'Bearer ' + token,
      }),
    };
    this.http.get(userDetailsApiUrl, options).subscribe((Response) => {
      if (Response) {
        this.userDetails = Response['data'];
        this.displayData();
      }
    });
  }

  displayData() {
    // this.userDetails = this.demoData;
    this.isDataLoaded = true;
    let details = this.userDetails;

    let Ids: any = [];
    let parentId: any = [];
    let parentData: any = [];
    let dataArr: any = [];
    let finalData: any = {};
    let vals: any = [];

    for (let i = 0; i < details.length; i++) {
      if (details[i]['parentId'] == 0) {
        parentId.push({
          userId: details[i]['userId'],
          parentId: details[i]['parentId'],
        });
        parentData.push(details[i]);
      } else {
        let valueExists = $.inArray(details[i]['parentId'], Ids);
        if (valueExists == -1) {
          Ids.push(details[i]['parentId']);
        }
      }
    }

    for (let j = 0; j < Ids.length; j++) {
      for (let i = 0; i < details.length; i++) {
        if (Ids[j] == details[i]['parentId']) {
          vals.push(details[i]);
          finalData[Ids[j]] = vals;
        }
      }
      let existing = parentData[0];
      let temp = {
        userId: Ids[j],
        childData: vals,
        imsuserId: existing['imsuserId'],
        name: existing['name'],
        familyName: existing['familyName'],
        userName: existing['userName'],
        emailIdPrimary: existing['emailIdPrimary'],
        contactNumberPrimary: existing['contactNumberPrimary'],
        reportingManager: existing['reportingManager'],
        teamName: existing['teamName'],
        teamCount: existing['teamCount'],
        createdBy: existing['createdBy'],
        createdOn: existing['createdOn'],
        parentId: existing['parentId'],
        isActive: existing['isActive'],
        timeZoneId: existing['timeZoneId'],
        languageId: existing['languageId'],
        dataAccessTypeId: existing['dataAccessTypeId'],
        orgId: existing['orgId'],
        currencyCode: existing['currencyCode'],
        currencyLocale: existing['currencyLocale'],
        jobTitle: existing['jobTitle'],
        userHierarchy: existing['userHierarchy'],
        teamUsers: existing['teamUsers'],
      };
      dataArr.push(temp);
      vals = [];
    }

    for (let i = 0; i < dataArr.length; i++) {
      if (dataArr[i]['parentId'] == 0) {
        let temp = dataArr[i];
        dataArr = [temp];
      }
    }

    $.each(finalData, function (i, item) {
      for (let i = 0; i < item.length; i++) {
        for (let j = 0; j < Ids.length; j++) {
          if (item[i]['userId'] == Ids[j]) {
            let existing = item[i];
            let tempKey = item[i]['userId'];
            item[i] = {
              childData: finalData[Ids[j]],
              [tempKey]: item[i],
              userId: existing['userId'],
              imsuserId: existing['imsuserId'],
              name: existing['name'],
              familyName: existing['familyName'],
              userName: existing['userName'],
              emailIdPrimary: existing['emailIdPrimary'],
              contactNumberPrimary: existing['contactNumberPrimary'],
              reportingManager: existing['reportingManager'],
              teamName: existing['teamName'],
              teamCount: existing['teamCount'],
              createdBy: existing['createdBy'],
              createdOn: existing['createdOn'],
              parentId: existing['parentId'],
              isActive: existing['isActive'],
              timeZoneId: existing['timeZoneId'],
              languageId: existing['languageId'],
              dataAccessTypeId: existing['dataAccessTypeId'],
              orgId: existing['orgId'],
              currencyCode: existing['currencyCode'],
              currencyLocale: existing['currencyLocale'],
              jobTitle: existing['jobTitle'],
              userHierarchy: existing['userHierarchy'],
              teamUsers: existing['teamUsers'],
            };
          }
        }
      }
    });

    this.mainData = dataArr;
    console.log(this.mainData);

    $('#userData').fadeToggle();
    $('.loader').fadeToggle();
  }

  openDialog(name, userId, username, fName, email, contact, created) {
    $('#userDetails').slideDown();
    $('.backdrop').fadeIn();

    let vals = {
      name: name,
      userId: userId,
      username: username,
      fName: fName,
      email: email,
      contact: contact,
      created: created,
    };

    Object.keys(this.keys).forEach(function (key) {
      $('[dataKey=' + key + ']').html(vals[key]);
    });
  }

  closeDialog() {
    $('#userDetails').slideUp();
    $('.backdrop').fadeOut();
  }

  ngOnInit(): void {
    this.getAccessToken();
    $('#userDetails, .backdrop').hide();
  }
}
